version: '3'

vars:
  PROTOC_IMAGE: '{{.PROTOC_IMAGE | default "protoc"}}'

tasks:
  format:
    desc: Format code
    cmds:
      - buf format -w blotservice/v1beta1/*.proto

  lint:
    desc: Lint proto files
    cmds:
      - buf lint

  lock:
    desc: Lock dependencies
    cmds:
      - buf mod update

  breaking:
    desc: Check for breaking changes
    dir: ../../..
    cmds:
      - buf breaking --against '.git#branch=main'

  generate:
    desc: Generate code with protoc plugins
    cmds:
      - task: lock
      - task: format
      - task: lint
      # - task: breaking
      - buf generate
