version: '3'

tasks:
  smoke-test-get-game:
    desc: Smoke test get game
    vars:
      BLOT_SERVICE_ADDRESS: '{{.BLOT_SERVICE_ADDRESS | default "127.0.0.1:8080"}}'
    cmds:
      - |
        grpcurl -vv -plaintext -d '{
          "game_id": "1",
          "player_id": "1"
        }' {{.BLOT_SERVICE_ADDRESS}} blotservice.v1beta1.BlotService.GetGameForPlayer